name: My First Workflow

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: List files and display README
        run: |
            echo "Welcome to my first GitHub Action!"
            ls -ltra
            cat README.md
     
      - name: Generate ASCII ArtWork
        run: cowsay -f dragon "Run for cover, I am a DRAGON.... RAWR" >> dragon.txt